### ISSUE TITLE
Fusion

### ISSUE THREAD

**Issue by JimScope** [void-type/cmdMail#1]
If you need help you can merge the cmdMail repo with PowerM, use IMAP. Your repo inspired me. Contact me at lucia.77@nauta.cu

**Comment by void-type** [comment]
I'm super glad to hear that!

At first glance of the code, PowerM looks really robust and better organized. Good work.

I don't really work on cmdMail much anymore so it would be nice to redirect future users of cmdMail to something more actively developed like PowerM.

I'll keep this issue open as a reminder to myself and others to check it out. I'll close it when I've updated the readme. 

In the meantime, feel free to use whatever you need from this repo.
